server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
     server:
      native:
        searchLocations: file:///home/smayan/projects/fullstack/configserver/src/main/resources/config/licensesrvc,
                         file:///home/smayan/projects/fullstack/configserver/src/main/resources/config/orgsrvc


