server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
     server:
      native:
        searchLocations: file:///usr/local/configure/licensesrvc,
                         file:///usr/local/configure/orgsrvc


